name: FTP ile Canlıya Al (Deploy)

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Kodu Depodan Çek
      uses: actions/checkout@v4

    - name: 🟢 Node.js Kur
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 📦 Paketleri Yükle
      run: npm install

    - name: 🛠️ Build Al
      run: npm run build

    - name: 📂 dist klasörünü FTPS ile Yükle
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        local-dir: ./dist/
        server-dir: ./public_html/
        state-name: .ftp-deploy-sync-state.json
